#!/usr/bin/env bash

# make user environment match ~/.config/nixpkgs/jmc.nix
# 
# This will remove any packages you've installed with nix-env
# but have not added to user.nix. To see exactly what this
# will do, run:
# 
#     sd nix diff

set -euo pipefail

nix-env -I .nix-defexpr/channels/ -irf ~/.config/nixpkgs/jmc.nix
